Fix broken link in documentation
drupal-graphql/graphql pull request #1023
Opened 2020-06-15 19:55 UTC by sixtyniner-official

PR for #1022

2020-06-22 18:42 UTC, joaogarin approved these changes

2020-06-24 13:46 UTC, klausi requested changes
Makes sense, that way we avoid a redirect. Would not say the link is broken, but avoiding redirects is good.

Can you also improve the link label to be consistent?

2020-06-24 13:46 UTC, klausi commented on README.md
> +* Documentation: [https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x](https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/)
We should also improve the link in the label

2020-11-06 09:04 UTC, klausi commented
Will merge this now and fix the label in a follow-up.

2020-11-06 09:05 UTC, merged