Drupal 9 compatibility for 3.x
drupal-graphql/graphql pull request #1067
Opened 2020-08-14 15:31 UTC by hugovk

Fixes #1011.
Based on, replaces and closes #1012 (with thanks to @damienmckenna).

Because the GraphQL v4 module isn't compatible with Drupal 8, contains breaking changes and requires a lot of rewriting, it will help the community to be able migrate to Drupal 9 sooner and by changing fewer things at each step.

Also, v4 is still in beta and therefore not covered by the security advisory policy, so may be not ready for production.

Once migrated to D9, users will be able to perform the v4 upgrade.

The tests pass on Travis CI for Drupal 8.8, 8.9 and 9.0.

Our D8.9 site's own unit tests pass with these changes.

2020-08-31 16:46 UTC, carolpettirossi approved these changes
I created a patch from #1067 and applied successfully to 3.x-dev.  :tallyhappy: 

Upgrade status marks as green. However, few warnings that could be fixed (maybe in a separate issue?)
![image (6)](https://user-images.githubusercontent.com/1932735/91744792-60cbac00-eb90-11ea-898b-328f752db87b.png)

2020-09-18 09:55 UTC, acha5066 approved these changes
I have tested this PR with 9.0.6 and all my queries and mutations are working as expected. Nice work! 

The warnings mentioned seem to be related to Symfony rather Drupal so they shouldn't be blockers

2020-09-25 11:04 UTC, gheydon requested changes

2020-09-25 11:04 UTC, gheydon commented on modules/graphql_core/graphql_core.info.yml
> +  - graphql
I know this is small, but we should be using the new format for dependencies, `graphql:graphql`

2020-09-25 11:04 UTC, gheydon commented on modules/graphql_core/tests/modules/graphql_block_test/graphql_block_test.info.yml
>    - block_content
As above

2020-09-25 11:04 UTC, gheydon commented on modules/graphql_core/tests/modules/graphql_breadcrumbs_test/graphql_breadcrumbs_test.info.yml
>  - graphql_breadcrumbs
See above

2020-09-25 11:04 UTC, gheydon commented on modules/graphql_core/tests/modules/graphql_requests_test/graphql_requests_test.info.yml
>  - graphql_core
Again

2020-09-25 11:04 UTC, gheydon commented on modules/graphql_core/tests/modules/graphql_test_menu/graphql_test_menu.info.yml
>    - system
again.

2020-09-25 11:04 UTC, gheydon commented on tests/modules/graphql_enum_test/graphql_enum_test.info.yml
>  - graphql
...

2020-09-25 11:04 UTC, gheydon commented on tests/modules/graphql_override_test/graphql_override_test.info.yml
>  - graphql_plugin_test
...

2020-09-25 11:04 UTC, gheydon commented on tests/modules/graphql_test/graphql_test.info.yml
>  - graphql
...

2020-10-14 11:51 UTC, bartlangelaan commented on modules/graphql_core/graphql_core.info.yml
> +package: Testing
Why? This is not a 'Testing' package - it is a normal submodule that is meant to be installed by users.

2020-10-29 14:54 UTC, hugovk commented
Merged in https://github.com/drupal-graphql/graphql/pull/1102 and released in https://www.drupal.org/project/graphql/releases/8.x-3.1 🎈

2020-10-29 14:54 UTC, closed without merging