#1151 - return an empty array instead of NULL when there are no referenced entities
drupal-graphql/graphql pull request #1165
Opened 2021-02-12 11:05 UTC by hchonov

2021-02-17 14:13 UTC, klausi requested changes
Thanks, I think that makes sense!

We should also update the other return statements to never return NULL and use `[]` consistently, right?

I think we also need test coverage for this so that we cover this fix for the future.

2021-02-17 14:13 UTC, klausi commented on src/Plugin/GraphQL/DataProducer/Field/EntityReference.php
> +          return $entities;
instead of using a variable we should do `return [];`, that is more readable and then I don't need to double check what is in $entities.

2021-09-21 04:21 UTC, hchonov commented on src/Plugin/GraphQL/DataProducer/Field/EntityReference.php
> +          return $entities;
done

2021-10-07 11:40 UTC, klausi commented
Thanks, then only the test coverage is missing I think?

2022-02-13 18:20 UTC, klausi commented
Continued in #1265

2022-02-13 18:20 UTC, closed without merging