Multiple critical performance improvments.
drupal-graphql/graphql pull request #1314
Opened 2022-11-09 14:57 UTC by ayalon

Multiple performance improvements:

- Disable schema validation on every request
- use `noLocation` to avoid recursions
- Cache extended schema after schema extension completed.

2023-07-26 14:31 UTC, Kingdutch requested changes
While I understand that these changes make things faster, there's also a few things that cause these changes not to be mergeable as-is and I think larger changes are required.

We don't know when a schema comes from the cache and when it's loaded from disk for the first time. The current change disables validation in all cases, but it's important that the schema is at least validated at some point.

Your change _always_ removes location data, but there are cases when location data might be very useful, for example when developing the schema. Additionally there may be production cases (like profiling) which might want location data too. So always disabling it is not an option. We'll have to identify when it's appropriate to disable, or create the right configuration for end users.

I'm not entirely sure what your change for the schema extension is trying to do, but it appears as if we're rebuilding the schema entirely, rather than only building the extension on top of an existing schema? This feels like it might also need a rethink (or a better explanation of what's happening).

EDIT: Ah the original issue has more explanation of what's going on :)

2023-11-12 10:26 UTC, klausi reviewed
Thanks, I will try to rewrite this a bit in a separate PR

2023-11-12 10:26 UTC, klausi commented on src/Plugin/GraphQL/Schema/SdlSchemaPluginBase.php
> +    $options = ['assumeValid' => TRUE];
we should only do this in prod, so we should check `empty($this->inDevelopment)`

2023-11-12 10:26 UTC, klausi commented on src/Plugin/GraphQL/Schema/SdlSchemaPluginBase.php
> +  public function getExtensionSchemaAst($schema, $extendSchema) {
this is confusing now, we already cache an AST in `getExtensionDocument()`. here we cache something again, why?

2023-11-12 10:26 UTC, klausi commented on src/Plugin/GraphQL/Schema/SdlSchemaPluginBase.php
> +    $schema_string = SchemaPrinter::doPrint($schema);
this is clever, I like the idea! We construct a final AST with all extensions and then cache that :+1:

2024-05-15 15:29 UTC, klausi commented
This was done, closing.

2024-05-15 15:29 UTC, closed without merging