Fix apq with page caches
drupal-graphql/graphql pull request #1317
Opened 2022-12-06 19:24 UTC by dbosen

This is aiming to resolve #1316 and #1315.

The reason why I want to fix both in one PR is because I started with writing tests for it. And both tests need to be BrowserTestBase tests, because otherwise we would not have requests, that create page cache (at least I did not find a way to write a kernel test).

Since no BrowserTestBase tests are in the module yet, 99% of the PRs would be identical, or they would have to be stacked.

For now this is JUST the tests, without the fixes. But I will add each proposed fix as a separate commit to this  PR later.

2023-04-13 12:20 UTC, pmelab requested changes
Thank you! We just faced exactly the same problem!
I left one comment.

@klausi : do you have any other remarks on this?

Also, is nobody using GraphQL with persisted queries? Thats a pretty obvious problem.

2023-04-13 12:20 UTC, pmelab commented on src/EventSubscriber/ApqSubscriber.php
> +      );
The problem is not specific to APQ. We are using a custom persisted query plugin, and it suffers from the same problem. I think this should go to a more generic place. Every GraphQL query that is run via `GET` will face this issue.

2023-04-13 12:22 UTC, pmelab commented on src/EventSubscriber/ApqSubscriber.php
> +      );
Actually, I would just rename this event subscriber and loosen the condition at the top.

2023-04-13 15:10 UTC, klausi requested changes
Thanks a lot, looks really nice! I have some suggestions to make this change a bit lighter.

2023-04-13 15:10 UTC, klausi commented on .github/workflows/testing.yml
> +          guzzlehttp/guzzle:^7.4.5
Guzzle is already part of Drupal core, so we don't need this line?

2023-04-13 15:10 UTC, klausi commented on phpunit.xml.dist
> +      <file>./tests/TestSuites/FunctionalTestSuite.php</file>
I'm torn on this: so far we could avoid long running functional tests, which makes our testing easier to understand and faster to run. On the other hand it is nice to test full real requests, but do we need it?

2023-04-13 15:10 UTC, klausi commented on src/EventSubscriber/ApqSubscriber.php
> +      );
Agreed! Maybe in Executor::doExecuteCached()?

2023-04-13 15:10 UTC, klausi commented on tests/modules/graphql_testing_schema/graphql/testing.graphqls
> +  article(id: Int!): Article
Is this a copy of the example module? Can we use the example module instead for testing? That way we also ensure the example module works, yay! And we avoid code duplication.

2023-04-13 15:10 UTC, klausi commented on tests/src/Functional/GraphQLFunctionalTestBase.php
> +abstract class GraphQLFunctionalTestBase extends BrowserTestBase {
we have a HttpRequestTrait that we use in the kernel tests, can we use that one to test the request/response workflow? Maybe we need to enhance it a bit?

Then we would not need to invent a new function test category here.

2023-04-14 10:07 UTC, pmelab commented on phpunit.xml.dist
> +      <file>./tests/TestSuites/FunctionalTestSuite.php</file>
Technically it should be enough to run a kernel test against the `http_kernel` service?

2023-05-30 07:02 UTC, dbosen commented
Thanks for the review! I am going to take a look at the requested changes.

2023-05-30 07:09 UTC, dbosen commented on phpunit.xml.dist
> +      <file>./tests/TestSuites/FunctionalTestSuite.php</file>
I have to admit I can't remember why I was not able to do the tests without funtional tests. But I think I failed getting the page caches to work was the problem. But I am trying to retrace my steps now

2023-11-09 07:43 UTC, nissen-chris commented on .github/workflows/testing.yml
> +          guzzlehttp/guzzle:^7.4.5
I heard this a couple of times in the Drupal community but that is not how composer should be used as far as I know.
Please have a look at this article from composer:
https://getcomposer.org/doc/01-basic-usage.md

A package should be required as soon as the project described in the `composer.json` file is using something from that package. If packages are also required in some dependencies of your project they will be resolved by composer automatically unless they are conflicting f.e.: one dependency of your project might require a newer version and you haven't changed your custom code yet to utilize the newer version of the dependency.

2024-03-21 14:56 UTC, klausi commented on .github/workflows/testing.yml
> +          guzzlehttp/guzzle:^7.4.5
OK, it should not matter much anyway since this is only used for testing anyway.

2024-03-21 15:10 UTC, klausi commented on phpunit.xml.dist
> +      <file>./tests/TestSuites/FunctionalTestSuite.php</file>
OK, then please try an attempt to execute this with the kernel tests HttpRequestTrait as mentioned.

2024-03-21 15:12 UTC, klausi commented
Thanks, can you answer all the inline comments from above and click "resolve" if they are done in your opinion?

The biggest blocker here is adding the Functional tests, which I would like to avoid if we can.

2024-04-02 13:36 UTC, dbosen commented
I have been able to replace the functional tests. But I also had to implement a different approach to solve the dynamic page cache issue.

The page cache fix is basically the same as before, but the dynamic page cache fix was not really working, as I found out while trying to write a new test for it...

So, I basically turn off dynamic page cache for the graphql requests. I think that is totally fine. Dynamic page cache does not seem to be the right thing for APQ requests anyway.

But I think, @pmelab and @IT-Cru might want to test this new approach in their projects again, to make sure it still works for them.

2024-04-03 15:37 UTC, dbosen commented
The last commit was done by @alexpott, not by me! He found a way to correctly add the cache context for  the dynamic page cache.

This looks quite good now I think!

2024-04-06 15:46 UTC, klausi commented on tests/src/Kernel/Framework/AutomaticPersistedQueriesDynamicPageCacheTest.php
> +    $result = $this->container->get('http_kernel')->handle($request);
why do we have to do all this repetitive request building and cannot use `$this->query()` from HttpRequestTrait?

Opened #1393 as this was also not correct in the previous test case.

2024-04-06 15:49 UTC, klausi commented on src/EventSubscriber/ApqSubscriber.php
> +          throw new Error('Provided sha does not match query');
I think Error is not correct here, should be UserError, right? We want to show this error to the graphql client that they sent something wrong.

Not the fault of this pull request, was already wrong before.

2024-04-06 15:52 UTC, klausi commented on src/EventSubscriber/ApqSubscriber.php
> +          throw new Error('Provided sha does not match query');
Interestingly we are asserting in the tests that the error message is coming out in the response, so it appears to be treated already as user error for some reason ... so we can leave this as is and don't care for now.

2024-04-06 15:58 UTC, klausi commented
Thanks a lot! I will merge this now and then simplify the test case a bit to use the `->query()` method.

2024-04-06 15:58 UTC, klausi approved these changes

2024-04-06 15:59 UTC, merged

2024-04-06 16:38 UTC, klausi commented
While converting the test cases I got super confused, why it fails on GET requests and shows a cached result. Need to find out why in #1394.

2024-04-08 15:11 UTC, klausi commented
Of course it was my fault, not using the result value from the method call.

All good now and will merge the follow-up test improvements soon.