#87 First attempt on RawFieldValueTest with questions.
drupal-graphql/graphql pull request #133
Opened 2017-06-02 08:38 UTC by blazeyo

2017-06-07 09:50 UTC, fubhy commented on modules/graphql_content/tests/src/Kernel/RawFieldValueTest.php
> +    // TODO Question: So the goal is to create a field formatter that can be
Correct.

2017-06-11 17:41 UTC, blazeyo commented
I've started a thread in the Files changed tab but it doesn't show up here, so adding a copy:

> The formatter has been implemented along with a deriver (needed because the formatter has to be applicable to all field types). It doesn't seem to be possible to return a raw array in viewElements method though. Drupal\Core\Render\Element triggers an error 'value' is an invalid render key..
> 
> Am I going in the right direction? Or maybe should I implement another graphql field plugin (similar to RenderedField)? If the latter, how should it be done?

2017-06-18 17:06 UTC, blazeyo commented
@fubhy The field plugin and the associated deriver have been implemented. The test worked with `type = "String"` and json encoding field values. Next step is to implement the type plugin and it's deriver. Some part of it is done but I'm not sure how to proceed.

Type plugin derivatives are generated here: https://github.com/fubhy/graphql-drupal/pull/133/files#diff-fc7012768b6f49380f6b9eb9585a578cR75. It doesn't look like the fields can just be added explicitly. Other types use either `data_type` or `interfaces`. Which way should the field properties (schema) be passed to the derivative definition?

2017-07-03 17:03 UTC, blazeyo commented
Raw values field type is ready for testing.

* Example usage: https://github.com/blazeyo/graphql-drupal/blob/feature/87-raw-field-data-formatter/modules/graphql_content/tests/queries/raw_field_values.gql
* Test: https://github.com/blazeyo/graphql-drupal/blob/feature/87-raw-field-data-formatter/modules/graphql_content/tests/src/Kernel/RawFieldValueTest.php

2017-07-04 08:43 UTC, fubhy requested changes

2017-07-04 08:43 UTC, fubhy commented on modules/graphql_content/tests/src/Kernel/RawFieldValueTest.php
> +  public function testRawValues() {
Can you write this test with a test data provider rather than logic? I prefer tests with nearly 0 logic.

2017-07-04 08:43 UTC, fubhy commented on modules/graphql_content/tests/src/Kernel/RawFieldValueTest.php
> +    foreach (static::$fields as $type => $fieldValues) {
Like... these loops. I'd rather have them simply as static lists in a data provider. Even if that means repeating the field names, etc.

2017-07-04 08:50 UTC, fubhy requested changes

2017-07-04 08:50 UTC, fubhy commented on modules/graphql_content/src/Plugin/Deriver/RawValueFieldItemDeriver.php
> +  // TODO Provide more mappings.
I think this should be moved to a place where we can make it more extendable. E.g. a service parameter?

2017-07-04 08:50 UTC, fubhy commented on modules/graphql_content/src/Plugin/Deriver/RawValueFieldItemDeriver.php
> +          'schemaColumn' => $columnName,
we use snake_case for plugin definition keys. (schema_column)

2017-07-04 08:50 UTC, fubhy commented on modules/graphql_content/src/Plugin/Deriver/RawValueFieldItemDeriver.php
> +    throw new TypeMappingNotFoundException("No mapping found for typed data type '$typedDataType'");
That should just default to "string" imho.

2017-07-04 08:50 UTC, fubhy commented on modules/graphql_content/src/Plugin/Deriver/RawValueFormatterDeriver.php
> +    $this->derivatives = [
Isn't $this->derivatives normally a keyed list of derivatives? In this case you made it $derivatives[0] = [...]

2017-07-04 08:50 UTC, fubhy commented on modules/graphql_content/src/Plugin/Field/FieldFormatter/RawValue.php
> +    // TODO The following code triggers and error in Drupal\Core\Render\Element::children,
You need to return a render array iirc.

2017-07-04 14:57 UTC, blazeyo commented
@fubhy Thanks for review. All comments have been addressed.

2017-07-04 14:58 UTC, blazeyo commented
BTW two follow up tickets have been created
- https://github.com/fubhy/graphql-drupal/issues/178
- https://github.com/fubhy/graphql-drupal/issues/179

2017-07-04 15:01 UTC, fubhy requested changes

2017-07-04 15:01 UTC, fubhy commented on modules/graphql_content/src/TypeMatcher.php
> +  protected static $mapping = [
I meant: Use a service parameter, not a whole service. Well actually a service WITH service parameters is even better ;). 

http://symfony.com/doc/current/service_container/parameters.html

2017-07-04 15:01 UTC, fubhy commented on modules/graphql_content/src/Plugin/Deriver/RawValueFormatterDeriver.php
> +    $this->derivatives = [
What about this one @blazeyo?

2017-07-04 15:38 UTC, blazeyo commented
@fubhy Type mapping is now a service parameter.

2017-07-04 17:38 UTC, fubhy requested changes

2017-07-04 17:38 UTC, fubhy commented on modules/graphql_content/graphql_content.services.yml
> +  graphql.type_matcher:
graphql_content.type_matcher

2017-07-04 17:38 UTC, fubhy commented on modules/graphql_content/graphql_content.services.yml
> +  graphql.type_map:
graphql_content.type_map

2017-07-06 16:34 UTC, blazeyo commented
I've found a problem with type deriver while working on another issue. Please hold on with merging. I hope to fix it tomorrow.

2017-07-11 07:53 UTC, fubhy commented
@blazeyo any news? would you also like to work on the entity reference thingy? (follow the graph into the next entity if the field is an entity reference field)?

2017-07-31 12:47 UTC, blazeyo commented
This PR is outdated and can be closed. Follow up: https://github.com/fubhy/graphql-drupal/pull/223

2017-07-31 12:47 UTC, closed without merging