feat(utility/fileupload): file_validate_image_resolution
drupal-graphql/graphql pull request #1342
Opened 2023-05-02 13:54 UTC by aurelianzaha

make it possible to validate the image resolution

file size and file extension validation is already in place

2023-05-02 14:01 UTC, klausi requested changes
Makes sense, can simplify a bit with the `??` operator?

2023-05-02 14:01 UTC, klausi commented on src/GraphQL/Utility/FileUpload.php
> +      $maxResolution = !empty($settings['max_resolution']) ? $settings['max_resolution'] : 0;
```suggestion
      $maxResolution = $settings['max_resolution']) ?? 0;
```

2023-05-02 14:13 UTC, klausi commented
Hm, but will this change be enough? `getUploadValidators()` is called only once, then the $validator array is passed to `prepareFilename()`, but it is never looped over?

Can you add a test case to UploadFileServiceTest?

We copied the code from Drupal core FileItem, how does on image file item handle this? I guess it is done in ImageWidget, that's why it is missing.

2023-05-02 14:25 UTC, klausi commented
Another problem is that you cannot use `file_validate_image_resolution()` fully because it invokes the drupal message system when changing the scale of an image. That is not ideal, as it starts a user session that you don't need.

So probably you will need a copy of file_validate_image_resolution() as method in our file upload service.

2023-05-04 11:38 UTC, aurelianzaha commented
> Hm, but will this change be enough? `getUploadValidators()` is called only once, then the $validator array is passed to `prepareFilename()`, but it is never looped over?
> 
> Can you add a test case to UploadFileServiceTest?
> 
> We copied the code from Drupal core FileItem, how does an image file item handle this? I guess it is done in ImageWidget, that's why it is missing.

yes, that is enough, the $validators array is use here
https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/GraphQL/Utility/FileUpload.php#L261
this is where the loop happens

2023-05-04 11:59 UTC, aurelianzaha commented
@klausi I made a copy of `file_validate_image_resolution` do we still need the tests ?

2023-05-04 14:23 UTC, klausi reviewed
Ah great, overlooked file_validate().

Yes, please add a test!

2023-05-04 14:23 UTC, klausi commented on graphql.module
> +function graphql_file_validate_image_resolution(FileInterface $file, $maximum_dimensions = 0, $minimum_dimensions = 0) {
instead of doing this as function - can you add it as method to our file upload service class? We want to avoid new procedural code in Drupal9.

2023-05-17 07:53 UTC, klausi requested changes
Thanks, approach makes sense. I see some minor issues and please add a test case for minimum resolution settings as well that you get out an error message.

2023-05-17 07:53 UTC, klausi commented on src/GraphQL/Utility/FileUpload.php
> +      $errors += $this->validateFileImageResolution($file, $maxResolution, $minResolution);
we should only invoke this method if we have the min/max resolution settings? That avoids calling the image factory with arbitrary files where we know those are not images.

2023-05-17 07:53 UTC, klausi commented on tests/src/Kernel/Framework/UploadFileServiceTest.php
> +   * Tests that the file dimension is not be larger than the limit.
"Tests that a larger image is resized to maximum dimensions."

2023-05-17 07:53 UTC, klausi commented on src/GraphQL/Utility/FileUpload.php
> +  protected function validateFileImageResolution(FileInterface $file, $maximum_dimensions = 0, $minimum_dimensions = 0) {
return type hint missing: array

2023-05-17 09:47 UTC, klausi approved these changes
Looks good, thanks!

2023-05-17 09:48 UTC, merged