fix(dataproducer): CurrentUser result is uncacheable
drupal-graphql/graphql pull request #1417
Opened 2024-08-05 21:52 UTC by pfrenssen

Fixes #1351

2024-08-30 17:40 UTC, klausi requested changes
Thanks a lot, approach makes sense. Only the test is not correct to me.

Please continue this work in a new merge request on drupal.org, we recently moved development there to assign issue credits there. https://www.drupal.org/project/issues/graphql

2024-08-30 17:40 UTC, klausi commented on config/schema/graphql.schema.yml
> +    dataproducer_allow_current_user_caching:
I don't think we need this setting. We can add caching, as long as we achieve the same behavior this will not be a compatibility break.

2024-08-30 17:40 UTC, klausi commented on tests/src/Kernel/DataProducer/CurrentUserTest.php
> +  protected function executeDataProducer($id, array $contexts = []) {
but this does not actually test the caching.

We need to test 2 things:
1) Repeated calls to get the current user return a cached result
2) when the user cache context is cleared you get an uncached result

I think just calling the dataproducer is not enough. Check out ResultCacheTest which does some unholy mocking, but should be the right approach.

2025-10-17 13:02 UTC, pfrenssen commented
Moved to https://www.drupal.org/project/graphql/issues/3552851

2025-10-17 13:02 UTC, closed without merging