WIP: Metatag integration.
drupal-graphql/graphql pull request #145
Opened 2017-06-12 03:40 UTC by pmelab

Hacked first try of a metatag integration.

We might have to generalise the "extraction" pattern. It gets quite often.

2017-06-13 10:32 UTC, fubhy requested changes

2017-06-13 10:32 UTC, fubhy commented on modules/graphql_metatag/src/Plugin/GraphQL/Fields/Metatags.php
> +      //
I don't see that anywhere!

2017-06-13 10:32 UTC, fubhy commented on modules/graphql_metatag/src/Plugin/GraphQL/Fields/MetaValue.php
> +    if (is_array($value) && array_key_exists('value', $value)) {
I don't know... I find this weak type checking weird. Can we use a container object for $value?

2017-06-13 10:32 UTC, fubhy commented on modules/graphql_metatag/src/MetatagExtractor.php
> +    if ($tag['#tag'] === 'meta') {
I think we should transform the metatags into container objects here.

2017-06-13 10:33 UTC, fubhy commented
I don't find this hacky at all. Sure, we should look at the performance (we are doing a lot of subrequest stuff in quite a few different resolvers now) but I don't have a problem with this implementation at all.

2017-06-13 12:51 UTC, pmelab commented on modules/graphql_metatag/src/Plugin/GraphQL/Fields/Metatags.php
> +      //
Because it has been removed since the language as become a request-global state. As this comment should be.

2017-06-13 13:02 UTC, pmelab commented
My issues with the current state:
- I'm not sure it even supports all necessary metatag types.
- It introduces GraphQL types for different kinds of metatags (property, link and simple), which might not be a very elegant solution. The proper solution depends on the previous issue.
- Based on the [Rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) we should unify this sub-request pattern and make sure it works together languages and possible other global states (domains ...). Thats a touchpoint with #148. And #130 should resolve the performance issue.

2017-06-20 20:57 UTC, chuongle commented
@pmelab Just wanna let you know I tested this and it works with Metatag Open Graph and Metatag: Twitter Cards.

2017-08-13 08:55 UTC, pmelab commented
I think this branch should eventually become a separate module. It's enough if the main GraphQL includes extensions that cover core.

2017-08-21 12:04 UTC, peterkeppert commented
I was testing this approach and it works very nice, however it seems that caching has some issues.

If I make a graphql request for meta tags on a node path, it gets cached. If I update node title (used as a token in page title meta tag) or update default title and description for content and repeat the same request, I see the outdated metatags. To reproduce the issue, take care to request only the meta tags and not the given node alongside them - the cached response would be invalidated on node title change.

My experiment was conducted with nodes and page variants (we are integrating GraphQL with Panels and Metatag). I was able to correct the cache behavior with getCacheDependencies() in Metatags.php, but only in page variant specific manner.

`protected function getCacheDependencies($result, $value, array $args) {
    $metadata = new CacheableMetadata();
    if (!$value instanceof Url) {
      return [$metadata];
    }

    $route = $this->router->match($value->toString());
    $variant = !empty($route['page_manager_page_variant']) ? $route['page_manager_page_variant'] : NULL;
    if (empty($variant)) {
      return $metadata;
    }
    /* @var \Drupal\page_manager\Entity\PageVariant $variant */
    $key = $variant->getEntityType()->id() . '__' . $variant->id();
    $metatag_variant = MetatagDefaults::load($key);
    if (!empty($metatag_variant)) {
      $metadata->addCacheTags($metatag_variant->getCacheTags());
      $metadata->addCacheContexts($metatag_variant->getCacheContexts());
    }
    return [$metadata];
  }`

I am unsure how to correctly retrieve:
- entity bound to given URL - metatag_get_route_entity() does not help, since it doesn't currently take route as parameter
- metatag configuration for the given entity (content or configuration one)
for the solution to be universal.

2017-09-08 09:07 UTC, peterkeppert commented
In latest version of graphql, MetaTag interface (MetaTag.php) produces error, because 
`parent::__construct($configuration, $pluginId, $pluginDefinition);`
should be
`parent::__construct($configuration, $pluginId, $pluginDefinition, $schemaManager);`
Could you update?

2017-10-16 10:53 UTC, fubhy commented
We will add a separate module (graphql_metatag) in it's own d.o namespace for this if we need it in the future.

2017-10-16 10:53 UTC, closed without merging

2018-01-06 15:24 UTC, dan2k3k4 commented
@fubhy will the repository be created at: https://github.com/drupal-graphql/graphql-metatag ? 😄

2018-01-06 16:13 UTC, dan2k3k4 commented
As we have a client that requires metatags integration on frontend, I've pushed to a public temporary repository - code based on this PR, currently WIP as it doesn't work with the new beta version of GraphQL - https://github.com/AmazeeLabs/graphql-metatag