More specific name for view sorts
drupal-graphql/graphql pull request #184
Opened 2017-07-06 06:41 UTC by Leksat

The "name" key is used as a base name for creating the name of the enum type. So it should be pretty specific.

2017-07-08 13:54 UTC, fubhy commented
Let's instead change the logic for generating the enum type names so it does not use the field name but something else... like an additional array value.

2017-07-08 13:54 UTC, fubhy requested changes
See my other comment.

2017-07-10 08:00 UTC, Leksat commented
@fubhy, something like this?

2017-07-10 22:12 UTC, fubhy requested changes

2017-07-10 22:12 UTC, fubhy commented on modules/graphql_core/src/GraphQL/Traits/TypedPluginTrait.php
> +          var_dump($definition);
Whoops.

2017-07-10 22:13 UTC, fubhy commented on modules/graphql_core/src/GraphQLSchemaManager.php
> +        var_dump($def['definition']);
Whoops.

2017-07-10 22:14 UTC, fubhy commented on modules/graphql_views/src/Plugin/Deriver/ViewDeriver.php
> +            "enum_type_name" => graphql_core_camelcase([$id, 'SortByEnum']),
I think this should be SortBy{xxx}Enum

2017-07-10 22:14 UTC, fubhy commented
@Leksat Yes, along those lines. But pleas without the var_dump() :D

@pmelab what do you think?

2017-07-11 06:46 UTC, Leksat commented
Whoops, indeed :D

2017-07-12 12:55 UTC, merged