Pull information from xml data in text fields.
drupal-graphql/graphql pull request #197
Opened 2017-07-13 06:58 UTC by pmelab

Traverse xml structures stored in long text fields with XPath. 

**AKA:** *Death to paragraphs (module)*

2017-07-13 07:09 UTC, fubhy commented
Are you insane?

2017-07-13 07:13 UTC, pmelab commented
*The distance between insanity and genius is measured only by success.*

2017-07-13 14:38 UTC, rkoberg commented
This would be very useful for internal reports. For example, run XPaths like the following on the body (or certain content types, or any long text, or any using "full html" text format) field:
```
//img
//img[starts-with(@src, 'http')]
//a
//a[starts-with(@href, 'http')] <!-- get all external links -->
//a[starts-with(@href, '/')]
//a[contains(@href, 'example.com')]
//math <!-- pick out MathML instances for validation report -->
//div[contains(@class, 'modal')]
```
Great project!

2017-07-13 14:46 UTC, pmelab commented
@rkoberg Or simpler use cases like a "Table of contents" generated from all headers.
Or a "turn all images into a slideshow" ...

2017-07-24 04:59 UTC, fubhy requested changes

2017-07-24 04:59 UTC, fubhy commented on modules/graphql_xml/src/Plugin/GraphQL/Fields/XMLAttribute.php
> + *   arguments={ "name": "String" },
Whitespace

2017-07-24 04:59 UTC, fubhy commented on modules/graphql_xml/src/Plugin/GraphQL/Fields/XMLContent.php
> +      foreach ($value->childNodes as $child) {
I usually prefer loops like this as reducers.

2017-07-24 04:59 UTC, fubhy commented on modules/graphql_xml/tests/src/Kernel/XMLFieldTest.php
> + * @group graphql_boolean
graphql_xml

2017-08-21 13:08 UTC, merged