212 rename view
drupal-graphql/graphql pull request #213
Opened 2017-07-26 14:50 UTC by Pasqualle

2017-07-26 14:58 UTC, fubhy requested changes

2017-07-26 14:58 UTC, fubhy commented on src/Plugin/views/display/GraphQL.php
> +      // fix: move this GraphQL display plugin under graphql_views module.
We can't move it there because this plugin can also be used with custom, n on generated schemas. And it should stay that way.

2017-07-26 14:58 UTC, fubhy commented on src/Plugin/views/display/GraphQL.php
> +      $graphql_query_name = graphql_core_camelcase([$viewId, $displayId, 'view']);
We use camelCase for all variables and everything basically.

2017-07-26 15:07 UTC, Pasqualle commented on src/Plugin/views/display/GraphQL.php
> +      $graphql_query_name = graphql_core_camelcase([$viewId, $displayId, 'view']);
hmm, I am not sure what you mean. What should be the fix here?
Is there another function to camelcase the name? Or the graphql_core_camelcase() function can be moved to graphql module? Or should the function be duplicated inside this file?

2017-07-31 12:29 UTC, fubhy requested changes

2017-07-31 12:29 UTC, fubhy commented on src/Plugin/views/display/GraphQL.php
> +    $graphql_query_name = strip_tags($this->getOption('graphql_query_name'));
We use camel-case in our whole codebase.

2017-07-31 12:29 UTC, fubhy commented on src/Plugin/views/display/GraphQL.php
> +  public function getGraphQLQueryName() {
This method needs a method header.

2017-07-31 12:29 UTC, fubhy commented on src/Plugin/views/display/GraphQL.php
> +  public function buildOptionsForm(&$form, FormStateInterface $form_state) {
We use camel-case everywhere (form_state => formState)

2017-07-31 12:29 UTC, fubhy commented on graphql.module
> +function graphql_camelcase($components) {
Can you add another commit that changes all usages of graphql_core_camelcase and graphql_core_propcase to the new versions?

2017-08-02 07:08 UTC, merged

2017-08-02 07:08 UTC, fubhy commented
Thanks