Integrated deferred resolving.
drupal-graphql/graphql pull request #222
Opened 2017-07-31 11:46 UTC by pmelab

This pull requests prepares the processor for deferred resolving, adds tests and introduces a new `BatchedFieldInterface` that can be implemented by fields that should be evaluated in batches (multiple at once).

The last addition is purely optional. It's still possible to simply return a deferred resolver, but with this interface, the module will take the heavy lifting of queuing and grouping deferred resolve operations.

2017-07-31 15:03 UTC, fubhy requested changes

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/src/BatchedFieldResolver.php
> +  protected $queue;
Field docs.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/src/BatchedFieldResolver.php
> +      throw new \Exception("Requesting unregistered batched result: " . serialize($key));
I usually prefer sprintf() for these.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/src/BatchedFieldResolver.php
> +    return [$id, max(array_keys($this->queue[$id]))];
We could also return a callable here.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/src/BatchedFieldResolver.php
> +  public function resolve(array $key) {
If we use a callable for this, we should change this method to use 2 explicit args instead of an array.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +    return "users";
Single quotes, dude. This is important.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +    return "users";
Also, do we need a method to generate more... "unique" ids for this? Maybe as a function on the batch service? Or do we need to make these available and explicit across different field plugins?

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +
Blank line.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +  public function prepareBatch(array $batch) {
Better name this resolveBatch()?

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +  public function prepareBatch(array $batch) {
It fetches the data and splits it up... So actually it does more than just preparation?

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +    else {
Redundant else.

2017-07-31 15:03 UTC, fubhy commented on modules/graphql_core/src/GraphQL/BatchedFieldInterface.php
> +   * The `$batch` input argument is a list of associative arrays with "value"
Should that array also contain the $resolveInfo of each of the values?

2017-07-31 15:07 UTC, pmelab commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +    return "users";
I thought about adding the class implementing `prepareBatch`. We have to make sure two overrides don't get evaluated together.

2017-07-31 15:10 UTC, pmelab commented on modules/graphql_core/src/GraphQL/BatchedFieldInterface.php
> +   * The `$batch` input argument is a list of associative arrays with "value"
Left out intentionally, since it's library specific and we should drop it anyway as soon as we do the big split.

2017-07-31 15:11 UTC, fubhy commented on modules/graphql_core/src/GraphQL/BatchedFieldInterface.php
> +   * The `$batch` input argument is a list of associative arrays with "value"
it's not library specific.

2017-07-31 15:12 UTC, pmelab commented on modules/graphql_core/tests/modules/graphql_batched_test/src/Plugin/GraphQL/Fields/Users.php
> +  public function prepareBatch(array $batch) {
True. But `resolve` is still called, but with the values "prepared" here.

2017-08-11 13:16 UTC, pmelab commented
Updated to library v1.5, all green.
IMHO RTBC
Abbreviations are awesome.

2017-08-11 13:27 UTC, merged