in case User don’t use expose filter, we want use the default filter.
drupal-graphql/graphql pull request #230
Opened 2017-08-07 11:21 UTC by ClemensSahs

this will fix the error from the PR #185

2017-08-07 12:23 UTC, ClemensSahs commented
currently only Drupal 8.4 fail

Drupal\taxonomy\Tests\TaxonomyTestTrait is deprecated in Drupal 8.4.0 and will be removed before Drupal 9.0.0. Instead, use \Drupal\Tests\taxonomy\Functional\TaxonomyTestTrait: 1x

2017-08-07 17:27 UTC, fubhy requested changes

2017-08-07 17:27 UTC, fubhy commented on modules/graphql_views/tests/src/Kernel/ViewsTestBase.php
> +
Blank line.

2017-08-07 17:27 UTC, fubhy commented on modules/graphql_views/tests/src/Kernel/ViewsTestBaseDeprecationFix.php
> +
Blank line.

2017-08-07 17:27 UTC, fubhy commented on modules/graphql_views/tests/src/Kernel/ViewsTestBaseDeprecationFix.php
> +
Blank line.

2017-08-07 17:27 UTC, fubhy commented on modules/graphql_views/tests/src/Kernel/ViewsTestBaseDeprecationFix.php
> +
Blank line.

2017-08-08 11:24 UTC, pmelab commented
Thank you a lot!

2017-08-08 11:25 UTC, merged