WIP: Add queries hash to cache id.
drupal-graphql/graphql pull request #301
Opened 2017-09-05 14:13 UTC by pmelab

2017-09-05 18:22 UTC, fubhy commented on src/EventSubscriber/CacheSubscriber.php
> +    $queryHash = md5(serialize($request->attributes->get('queries')));
This should be a cache context instead, no? That's the whole point of cache contexts ;)

2017-09-05 18:22 UTC, fubhy requested changes
Instead of building the cache id manually, you should be using cache contexts.

2017-09-05 18:24 UTC, pmelab commented
Yes, this is just a quick fix we needed. Pushed it for reference.

2017-09-11 03:57 UTC, pmelab commented
This has been solved by #306.

2017-09-11 03:58 UTC, closed without merging