Added config entity for GraphQL query maps.
drupal-graphql/graphql pull request #38
Opened 2017-02-17 11:23 UTC by paranojik

Modified the route enhanced to accept an additional parameter for query map version id and for loading the map from config instead of file.

2017-02-17 11:46 UTC, fubhy reviewed
Very good job.  However, can you refactor the whole thing and replace all the snake_case variables to camelCase? I am using camelCase exclusively across the rest of the project. Thanks <3

2017-02-17 11:46 UTC, fubhy commented on src/Form/GraphQLQueryMapForm.php
> +    $form['version_id'] = [
Let's generate this instead of providing a form. No?

2017-02-17 11:46 UTC, fubhy commented on src/Form/GraphQLQueryMapForm.php
> +    if (empty($count)) {
Let's make this a .json file upload.

2017-02-17 11:46 UTC, fubhy commented on src/Form/GraphQLQueryMapForm.php
> +  public function addOne(array &$form, FormStateInterface $form_state) {
This is nice but realistically we would have an upload of a .json file and that would then be parsed and the queries from that json file woudl be added one by one.

2017-02-17 11:46 UTC, fubhy commented on src/Form/GraphQLQueryMapImportForm.php
> +namespace Drupal\graphql\Form;
Oh, now I see.. You built both! Nice. I don't think we need the other (manual) form for now. Can you split up this PR for just the upload form for now and submit the manual form separately? I need to think about that more.

2017-02-17 11:46 UTC, fubhy commented on src/QueryNotFoundException.php
> +
Unnecessary line break.

2017-02-17 11:46 UTC, fubhy commented on src/QueryNotFoundException.php
> + * @file
I don't want @file headers. They are redundant :).

2017-02-17 11:46 UTC, fubhy commented on src/QueryNotFoundException.php
> + * @file
Actually, I am not sure if we even need a dedicated exception type. What do you think?

2017-02-17 11:46 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +      'versionId' => NULL,
It's not a version Id. It's a hash. Let's just call it "version".

2017-02-17 12:55 UTC, paranojik commented on src/Form/GraphQLQueryMapForm.php
> +    $form['version_id'] = [
Yeah... I was thinking about that... but what if you want to make some small adjustments without modifying the version id? Or does that not make sense?

2017-02-20 08:22 UTC, fubhy requested changes
We are getting there. Looking great.

2017-02-20 08:22 UTC, fubhy commented on src/Form/GraphQLQueryMapForm.php
> +      \Drupal::service('renderer')->addCacheableDependency($form, $this->entity);
Why are we using \Drupal here?

2017-02-20 08:22 UTC, fubhy commented on src/Form/GraphQLQueryMapImportForm.php
> +      $form_state->setError($form['query_map_json'], $this->t('No file was uploaded.'));
$formState

2017-02-20 08:22 UTC, fubhy commented on src/Form/GraphQLQueryMapImportForm.php
> +    $form_state->setRedirect('entity.graphql_query_map.collection');
$formState

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
>      // Only keep numerical keys or 'query', 'variables', 'id'.
Comment needs to be adjusted (now also 'version')

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +      'query' => NULL,
should be empty string by default.

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +      'variables' => NULL,
should be empty array by default

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +    if (empty( $values['query']) && empty($values['id'])) {
There is an extra whitespace before $values['query']

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
>      }
I believe you didn't resolve the conflict in this method properly. I changed the code here a bit and you brought back some of the things I removed. Can you check the latest code in your merge target?

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +    if (empty($values['query']) && empty($values['id']) && empty($values['version'])) {
This condition is incorrect. We either need a 'query' OR we need ('id' AND 'version'). Let's change it to this:

so: empty($values['query']) && (empty($values['id']) && empty($values['version']))

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +  protected function getQuery($query, $id, $version) {
if we have a $query, just return it. If we don't have a $query, load by $id and $version.

```
if (!empty($query)) {
  return $query;
}

$queryMap = $this->entityTypeManager->getStorage('graphql_query_map')->load($version);
return !empty($queryMap[$id]) ? $queryMap[$id] : NULL;
```

2017-02-20 08:22 UTC, fubhy commented on src/Routing/QueryRouteEnhancer.php
> +  protected function getVariables($variables) {
This method was removed by me. Please check your conflict resolution.

2017-02-20 21:02 UTC, merged