Persisted queries support
drupal-graphql/graphql pull request #707
Opened 2019-01-08 09:47 UTC by chindris

The basis for implementing persisted queries, with no specific implementation of it (that will be part of a separate module).

2019-01-08 12:53 UTC, fubhy requested changes
Hi @chindris! Thanks for the work. One important thing imho from my PoV would be to make this fully configurable per schema. We probably want to come up with a pattern for this that we can then also use for other per-schema things like logging, performance tracing (e.g. a field level performance metric evaluator e.g. for newrelic, etc.)

2019-01-08 12:53 UTC, fubhy commented on graphql.links.menu.yml
> +graphql.query_maps:
All features (including query maps) should be scoped per Server/Schema. We will need the ability to configure per-schema "features" for other things in the future too so we should come with a pluggable pattern for this.

E.g. one thing we would also build with a pluggable approach would be logging and performance tracing for individual schemas.

2019-01-08 12:53 UTC, fubhy commented on graphql.services.yml
> +  graphql.query_provider:
We might want to make query providers plugins that one can attach to a schema/server.

2019-01-08 12:53 UTC, fubhy commented on graphql.services.yml
> +  graphql.query_provider:
Think e.g. about Search API and how it makes indexes extendable with facets, processors/transformers, etc.

2019-10-14 16:26 UTC, fubhy commented
Thanks for working on this. Feel free to reach out to me on Slack when you have a moment in the next few days to discuss the status of the PR etc. :-)

2020-04-28 07:46 UTC, rthideaway commented
@fubhy @pmelab what is the status of it? We'd like to use this feature. Can we somehow help with releasing it?

2020-04-29 09:54 UTC, klausi commented
@rthideaway can you do a code review of the pull request?

Travis tests are passing, only the code test coverage % decreases.

This is quite a big change, so we should think about how this could break existing sites that use the graphql module.

We should determine if the test coverage is good enough, and then we could merge?

2020-07-14 12:19 UTC, rthideaway commented
@klausi Regarding the test coverage. Persisted query plugin manager and persisted query plugins are tested well.

The missing test coverage relates to PersistedQueriesForm where the persisted query plugins are being enabled, which I would consider not that critical, as the form works by manual testing. The other missing test coverage relates to some of the new methods on Server entity, which couple of them would be covered by covering the form. The rest seems again good based on manual testing.

I would go for the merge.

2020-07-14 12:48 UTC, klausi commented
OK I agree, will merge this now.

2020-07-14 12:49 UTC, merged