WIP : Docs mutation plugins
drupal-graphql/graphql pull request #718
Opened 2019-01-25 17:07 UTC by joaogarin

Work in progress to document more detailed information on Mutations. Feedback welcome, this is all based on my experience going through tests and other places where i could find some information so highly appreciate feedback on things that can be wrong or misinforming people.

2019-01-25 17:25 UTC, joaogarin commented on doc/mutations/creating-mutation-plugins.md
> +The first step to create a mutation is to make the plugin, the graphql module provides a base class for creating new entities called **CreateEntityBase**. You should use implement a plugin that exten
type here in : 

```suggestion
The first step to create a mutation is to make the plugin, the graphql module provides a base class for creating new entities called **CreateEntityBase**. You should implement a plugin that extends this class when you want to create an entity directly without too much custom things in it.
```

2019-02-13 20:58 UTC, fubhy requested changes
I marked a few typos and grammaer issues as well as general style issues (back ticks for code references, variable names, etc.). Can you proofread the PR once again and fix the things I brought up?

Thanks, reaaally good job! I was a bit shocked about how much documentation you are adding here. Really cool!

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +The graphql module uses the [Drupal plugin system](https://www.drupal.org/docs/8/api/plugin-api/plugin-api-overview) for a lot of the extensibility features of plugins. So a lot of the times when you
for example

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +One of the most common things you will want to do when with mutations is to create, update and delete entities. These CRUD operations on entities where made as simple as possible to implement with th
"When with mutations"?

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +One of the most common things you will want to do when with mutations is to create, update and delete entities. These CRUD operations on entities where made as simple as possible to implement with th
"W*h*ere made as simple as possible"

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +One of the most common things you will want to do when with mutations is to create, update and delete entities. These CRUD operations on entities where made as simple as possible to implement with th
Just say that "were made as simple as possible to implement and only require you to extend some generic classes provided by the graphql_core module"

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +The first step to create a mutation is to make the plugin, the graphql module provides a base class for creating new entities called **CreateEntityBase**. You should implement a plugin that extends t
Finish the sentence after "to make the plugin". (Instead of a comma).

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +lets look at what the code for this plugin looks like :
Let's (capitalized and with a tick)

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can see a couple things here in this code that are particular interesting :
particularly

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can see a couple things here in this code that are particular interesting :
Redundant whitespace before the colon

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can see a couple things here in this code that are particular interesting :
Also, the 'here' seems redundant. "We can see a couple things in this code that are particularly interesting:"

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +Make sure that this plugin lives inside **```{{module_name}}//src/Plugin/GraphQL/http://Mutations/CreateArticle.php **
This markdown seems wrong (bold)

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +There is one method you should always implement when doing mutations, that is the **extractEntityInput** method which will be sort of a mapping between the arguments you pass to the mutation and the
Shouldn't use bold (**) but quote ticks instead to mark it as code.

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can see we are assigning the **title** that we are passing in the input (we will look at the ArticleInput after) to the title property in the entity, same for the **body**.
Same with title and body. Use code quotes.

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +Lets continue with our article example. In this case we implement a mutation to update a given article. Because we are updating a particular entity and we need to know which entity it is, we will nee
Let's (not Lets)

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +Lets continue with our article example. In this case we implement a mutation to update a given article. Because we are updating a particular entity and we need to know which entity it is, we will nee
Write "id" lower case and maybe put it in code quotes.

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +The first thing we noticed is we are now using **UpdateEntityBase** instead of "CreateEntityBase" as our parent class,
Again code quotes, not bold

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +The first thing we noticed is we are now using **UpdateEntityBase** instead of "CreateEntityBase" as our parent class,
"CreateEntityBase" should also be ``CreateEntiyBase``

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +we can also see that we use the same argument "Input" as above but we also have another argument called **id**. The Graphql Module will be smart enough to use that id to match to the right entity.
Same here for "Input' and "id"

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +we can also see that we use the same argument "Input" as above but we also have another argument called **id**. The Graphql Module will be smart enough to use that id to match to the right entity.
Write "module" lower case. Always write GraphQL instead of graphql, Graphql or graphQL (except in variable names of course).

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +The only thing left now is really to delete the entity right? This is the simples type of operation out of the 3, because we only need to give graphql the **id**, it will check if we can access that
"The only thing left is to delete the entity, right?"

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +The only thing left now is really to delete the entity right? This is the simples type of operation out of the 3, because we only need to give graphql the **id**, it will check if we can access that
FInish the sentence after "id". 

".. we only need to give the ``id``. It will check ..."

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can see that we use extend a "DeleteEntityBase" class and we only pass one argument, the id of the entity we want to delete, together with some of the anotations as we did previously with other mu
"We extend the ``DeleteEntityBase`` class and only require one argument: the id of the entity we want to delete. Additionally we add the required annotations as we previously did for the other mutations."

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +So we know from examples above that we need to define the arguments for mutations, much like a functions, mutations receive arguments that can be used to do whatever the mutation needs to do to work.
"We know from the examples above that we need to define the arguments for mutations. Similar to how a function, mutations receive arguments

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +So we know from examples above that we need to define the arguments for mutations, much like a functions, mutations receive arguments that can be used to do whatever the mutation needs to do to work.
Write "argument" lower case.

Make sure again to use `` back ticks to mark code blocks or names of classes, variables, etc.

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can see again that we namespace this plugin to our module name, in this case **graphql_examples** should be replaced by your own module name. This file should live inside **{{module_name}}/src/Plu
Use back ticks instead of asterisk (bold)

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can also see above that we only use anotations here to define the arguments inside the **fields** property. So we know that it receives a **title** and thats a "String" and we also receive a **bod
"annotations" (double n)

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/creating-mutation-plugins.md
> +We can also see above that we only use anotations here to define the arguments inside the **fields** property. So we know that it receives a **title** and thats a "String" and we also receive a **bod
"receives a ``title`` of type ``String`` and a ``body`` of type ``String``.

2019-02-13 20:58 UTC, fubhy commented on doc/mutations/custom-mutations.md
> +Not all mutations directly related to an entity, and often you might need to perform operations on a mutation that are not necessarily creating, updating or deleting an Entity in Drupal. For these ca
Not all mutations are directly related to an entity. 

Write "entity" lowre case.

2019-02-14 16:22 UTC, joaogarin commented
Passed it all through a spell checker, also addressed the topics mentioned here. thanks for the feedback! ; )

2019-03-06 11:16 UTC, merged