ImageStyle scheme with enums
drupal-graphql/graphql pull request #78
Opened 2017-05-05 22:48 UTC by webflo

Related to #58

---

I did some experiments with image style mostly for learning GraphQL. Still work in progress. What do you think? It this the right direction?

2017-05-05 22:53 UTC, webflo commented
Not sure how i should handle the original image. Duplicate all properties in the Image type?

2017-05-05 23:12 UTC, fubhy requested changes

2017-05-05 23:12 UTC, fubhy commented on modules/graphql_core/src/GraphQL/EnumPluginBase.php
> +    return $this->config->get('values');
Woops :P

2017-05-05 23:12 UTC, fubhy commented on modules/graphql_image/src/Plugin/GraphQL/Enums/ImageStyleId.php
> +      $items[] = [
I'd use the entity id as a key here. Just for good measure.

2017-05-05 23:12 UTC, fubhy commented on modules/graphql_image/src/Plugin/Deriver/ImageStyleDeriver.php
>    public function getDerivativeDefinitions($basePluginDefinition) {
This whole deriver can be deleted now. No?

2017-05-05 23:12 UTC, fubhy commented on modules/graphql_image/src/Plugin/GraphQL/Fields/ImageDerivative.php
> +      if (!file_exists($styleUri)) {
Yeah no. Let's not create files during the request. That's the job of the file controller upon an actual request.

Instead, you can pre-calculate / derive the expected width/height like this: 

```


  /**
   * Returns the expected image dimensions.
   *
   * @return array The image dimensions as an associative array.
   */
  protected function calculateDimensions() {
    if (isset($this->dimensions)) {
      return $this->dimensions;
    }

    $this->dimensions = [
      'height' => $this->height,
      'width' => $this->width,
    ];

    $this->style->transformDimensions($this->dimensions, $this->file->getFileUri());

    return $this->dimensions;
  }
```

2017-05-05 23:12 UTC, fubhy commented on modules/graphql_image/src/Plugin/GraphQL/Fields/ImageDerivative.php
> +          'mimeType' => $derivative->getMimeType(),
The mime type won't be changed by an image style. Right? At least it's very unlikely. Let's not expose it as part of one.

2017-05-05 23:12 UTC, fubhy commented on modules/graphql_image/src/Plugin/GraphQL/Fields/ImageDerivative.php
> +          'fileSize' => $derivative->getFileSize(),
We can't output the fileSize if we don't generate the file here. So... Skip it?

2017-05-05 23:12 UTC, fubhy commented
Yes, you are definitely on the right track.... A couple of remarks tho.

2017-05-05 23:21 UTC, webflo commented on modules/graphql_image/src/Plugin/Deriver/ImageStyleDeriver.php
>    public function getDerivativeDefinitions($basePluginDefinition) {
Yes

2017-05-05 23:23 UTC, webflo commented on modules/graphql_image/src/Plugin/GraphQL/Fields/ImageDerivative.php
> +          'mimeType' => $derivative->getMimeType(),
Its possible to have ImageEffects that change the filetype of the image.

2017-05-05 23:40 UTC, fubhy commented on modules/graphql_image/src/Plugin/GraphQL/Fields/ImageDerivative.php
> +          'mimeType' => $derivative->getMimeType(),
Right but it's unlikely. And therefore... Let's just leave it out too?

2017-05-05 23:40 UTC, fubhy commented on modules/graphql_image/src/Plugin/GraphQL/Fields/ImageDerivative.php
> +          'mimeType' => $derivative->getMimeType(),
Or do you really think it's feasible to have it generate the images on *request*?

2017-05-06 08:55 UTC, webflo commented on modules/graphql_image/src/Plugin/GraphQL/Enums/ImageStyleId.php
> +      $items[] = [
Can you explain the difference between ``id`` and ``name``?

2017-05-08 08:14 UTC, pmelab commented
I think we should keep the option to request the original image. Either by adding a new field or making the image style id optional.

2017-05-08 08:21 UTC, webflo commented
Yeah i work on it. I try so finde a object type which we could use for the ImageStyle and OriginalImage. Any good names?

2017-05-08 08:26 UTC, pmelab commented
`ImageFile`?
It will have width, height, file size and a url. That seems to be generic enough to justify a generic name. Since this type could be used by anything else emitting an image too.

2017-05-09 19:01 UTC, webflo commented
This is the new schema. Not sure if its better than the old one.

```
fieldImage {
  alt
  title
  original {
    url
    height
    width
  }
  large: derivative(style: large) {
    url
    height
    width
  }
  small: derivative(style: thumbnail) {
    url
    height
    width
  }
````

2017-05-09 19:34 UTC, webflo commented
I got rid of the original key by adding a ImageResource interface. New schema:

This is the new schema. Not sure if its better than the old one.

```
fieldImage {
  alt
  title
  url
  height
  width
  large: derivative(style: large) {
    url
    height
    width
  }
  small: derivative(style: thumbnail) {
    url
    height
    width
  }
````

2017-05-09 19:41 UTC, webflo commented
Needs test coverage for image style derivatives.

2017-05-09 21:27 UTC, fubhy approved these changes

2017-05-10 07:13 UTC, pmelab requested changes
Why is `ImageResource` an interface and not simply a type?

And another minor question: Most GraphQL enums I've seen so fare were uppercased. Not sure if this can be considered a coding standard.

2017-05-10 09:07 UTC, webflo commented
I thought its not possible to inherit types.

2017-05-10 09:16 UTC, webflo commented
@fubhy Can you explain the purpose of the ``InterfacePluginBase::resolveType``? The method is never called in my setup.

2017-05-10 09:17 UTC, pmelab commented
I'm sorry!
I overlooked that there is an interface **and** a type called `ImageResource`. So both the root image and the derivatives can be handled by the same fragment. Clever!

2017-05-10 09:24 UTC, pmelab commented
@webflo `resolveType` *has* to return a matching type for a given value.
For example the `Entity` interface checks if the value is an entity and returns the type plugin matching it's entity type and bundle.

In this case it works by accident because interface and type have the same name, and the processor prefers the type. Thats why resolve is never called.

To reduce confusion perhaps you should rename the interface and implement a real resolve method. Have a look at the Block interface as an example.

https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_block/src/Plugin/GraphQL/Interfaces/Block.php#L48-L58

2017-05-10 21:25 UTC, webflo commented
@pmelab Thanks for the explanation.

Next thing: Access checks. Should we do some access checking on the file entity. Or is it done on a higher level?

2017-05-10 21:58 UTC, fubhy commented
@webflo yes, we need access checks on referenced entities. Best is to simply invoke ->access('view') on those. It's funny that you mention that because I just realized we also don't check access on entity references currently :D. ping @pmelab

2017-05-11 03:38 UTC, pmelab commented
Why would we? All our editors are trustworthy! 😬 

#103

2017-05-16 03:56 UTC, pmelab approved these changes

2017-05-16 03:58 UTC, merged

2017-05-16 11:25 UTC, webflo commented
Awesome. Thanks!

2017-05-16 11:31 UTC, pmelab commented
Thank *you*! 😄