Add entity access checks to other entity loads.
drupal-graphql/graphql pull request #895
Opened 2019-09-09 18:00 UTC by ndrake0027

Adds entity access checking by default for loadMultiple, loadbyUUID, load translation(s)

2019-09-09 18:12 UTC, ndrake0027 commented
This is an extension of the work in #741. I was not 100% sure how to add some cacheability in the `entity_translation(s)` data producers. I was thinking about doing it with `access->CachePerUser()` but I don't really know what value (if any) that adds.

2019-09-10 11:47 UTC, fubhy requested changes

2019-09-10 11:47 UTC, fubhy commented on src/Plugin/GraphQL/DataProducer/Entity/EntityLoadMultiple.php
> +          if ($accessResult->isForbidden()) {
Wait. Should we check isAllowed() instead maybe? If we check isForbbiden() we allow access if the access check result is "meh, no clue" basically (if no access check handler explicitly returned TRUE / FALSE during access negotiation).

2019-09-10 11:47 UTC, fubhy commented on src/Plugin/GraphQL/DataProducer/Entity/EntityLoadMultiple.php
> +          if ($accessResult->isForbidden()) {
Should check with someone who knows the entity access api a bit better. What's best practice for that? Maybe @wimleers knows?

2019-09-10 11:48 UTC, fubhy commented
Looks good. Just need to validate that isForbidden or isAllowed is correct here.

2019-09-10 19:56 UTC, ndrake0027 commented on src/Plugin/GraphQL/DataProducer/Entity/EntityLoadMultiple.php
> +          if ($accessResult->isForbidden()) {
I thought we would want to look for explicit denial. My understanding is that if everything is nuetral then you get access but isAllowed will return false if access wasn't explicitly granted. Where as checking if for forbidden mean something explicitly denied access, basically not allowing access to just flow from one access hook to another.

2019-09-10 20:53 UTC, merged