Load translated referenced entities before array_filter and abstract logic in a trait
drupal-graphql/graphql pull request #974
Opened 2020-02-11 13:29 UTC by drupov

Currently the logic for resolving translated entity references is loading the translated versions in order to check the access to them. But at the end the default language version is returned. This PR makes sure to pass the proper language version(s) into the `array_filter` function that strips out the ones, where access is not given.

2020-02-22 09:31 UTC, fubhy requested changes

2020-02-22 09:31 UTC, fubhy commented on src/Plugin/GraphQL/DataProducer/Field/EntityReferenceTrait.php
> +  private function defer($type, $language, $bundles, $access, $accessUser, $accessOperation, $resolver, $context) {
I'd prefer this to be a protected method and also have a more descriptive name. By separating the function body of this function into smaller reusable chunks we'd also make it more customizable.

2020-02-22 09:32 UTC, fubhy commented
Thanks for this PR Dimitar! Looks good in general but I'd like to split up the function body into smaller reusable pieces and use a more descriptive function name.

2020-03-06 20:50 UTC, drupov commented
Abstracted also logic inside trait and added some comments to each method.

2021-08-04 09:40 UTC, chrfritsch commented
The patch works nicely for me. One thing that is a bit related:
In the plugin definition language is defined as multiple. I think it shouldn't be.

2021-08-16 14:23 UTC, klausi commented
This was merged in #1232 , thanks a lot for the upfront work here @drupov !

2021-08-16 14:23 UTC, closed without merging